### ISSUE TITLE
 Can I change prompts.py and add some entities myself ?

### ISSUE THREAD

**Issue by kaomita** [dylanhogg/llmgraph#7]

**Comment by dylanhogg** [comment]
You can add your own custom entities with prompts just by adding to the existing file `llmgraph/prompts.yaml`. No need to change any Python files.

For example add:
```
kaomitas-new-concept:
  system: You are highly knowledgeable about things that kaomita likes
  knowledgeable_about: things that kaomita likes
  entities: things
  entity: thing
  top_n: 5
```

And then run with a command similar to this: `llmgraph kaomitas-new-concept "https://en.wikipedia.org/wiki/<ADD-YOUR-ROOT-ENTITY-HEHE>"`

See additional commandline args here: https://github.com/dylanhogg/llmgraph?tab=readme-ov-file#required-arguments

I haven't fully tested adding new concepts with the pip installed llmgraph - you will may need to clone this repo and run it locally so that it picks up your edited prompts.yaml file with the concept and corresponding prompt you added. With pip you can probably do this by finding and editing the installed prompts.yaml where the library has been installed to.

Hope that helps.
